<?php 
defined('is_running') or die('Not an entry point...');


global $page, $config, $gpLayouts;
$layout_arr = $gpLayouts[isset($page->TitleInfo['gpLayout']) ?  $page->TitleInfo['gpLayout'] :  $config['gpLayout']];
$bs4 = strtolower($layout_arr['framework']['name']) == 'bootstrap' &&
	  preg_replace('/[^0-9]/', '', explode('.', $layout_arr['framework']['version'])[0]) == 4;

$section = array(); 


$section['values'] = array_merge(array( 
  'tabs' => array(
						0=> array('title'=>'Tab1', 'tab_content' =>'<h3>First tab</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ex dui, commodo ac augue id, suscipit dapibus massa. Quisque sit amet magna est. Nam pellentesque accumsan arcu, eu iaculis lorem dignissim id. Vivamus consectetur dictum rutrum. Morbi non venenatis odio. In suscipit id nibh nec venenatis. Donec vitae massa blandit, vehicula lorem at, varius risus. Donec mollis elit nec dolor dictum, quis placerat ante molestie. Nam suscipit eros sed posuere tempus. Pellentesque ipsum massa, viverra sit amet dignissim rhoncus, euismod a ligula. Ut nisi lacus, efficitur a auctor vitae, imperdiet quis eros.</p>', ),
						1=> array('title'=>'Tab2', 'tab_content' =>'<h3>Second tab</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ex dui, commodo ac augue id, suscipit dapibus massa. Quisque sit amet magna est. Nam pellentesque accumsan arcu, eu iaculis lorem dignissim id. Vivamus consectetur dictum rutrum. Morbi non venenatis odio. In suscipit id nibh nec venenatis. Donec vitae massa blandit, vehicula lorem at, varius risus. Donec mollis elit nec dolor dictum, quis placerat ante molestie. Nam suscipit eros sed posuere tempus. Pellentesque ipsum massa, viverra sit amet dignissim rhoncus, euismod a ligula. Ut nisi lacus, efficitur a auctor vitae, imperdiet quis eros.</p>', ),
						2=> array('title'=>'Tab3', 'tab_content' =>'<h3>Third tab</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ex dui, commodo ac augue id, suscipit dapibus massa. Quisque sit amet magna est. Nam pellentesque accumsan arcu, eu iaculis lorem dignissim id. Vivamus consectetur dictum rutrum. Morbi non venenatis odio. In suscipit id nibh nec venenatis. Donec vitae massa blandit, vehicula lorem at, varius risus. Donec mollis elit nec dolor dictum, quis placerat ante molestie. Nam suscipit eros sed posuere tempus. Pellentesque ipsum massa, viverra sit amet dignissim rhoncus, euismod a ligula. Ut nisi lacus, efficitur a auctor vitae, imperdiet quis eros.</p>', ),
						)
  
), $sectionCurrentValues );


$section['attributes'] = array(
  'class' => '',  
  // 'style' => '', // optional inline styles
);


$ti = 't'.crc32(uniqid("",true)); 
$a=' active';
$s='true';
$section['content'] = '<ul class="nav nav-tabs" role="tablist">';

 foreach ($section['values']['tabs'] as $key=>$tab){
		$section['content'] .= '<li class="nav-item"><a class="nav-link'.$a.'" data-toggle="tab" href="#'.$ti.$key.'" role="tab" aria-controls="'.$tab['title'].'" aria-selected="'.$s.'">'.$tab['title'].'</a></li>';
		$a =""; 
		$s='false';
 }
	$section['content'] .= '</ul>';
	
$a = $bs4 ?
	' show active' :	// Bootstrap 4
	' in active';  // Bootstrap 3
	
	$section['content'] .= '<div class="tab-content">';
 foreach ($section['values']['tabs'] as $key=>$tab){
	$section['content'] .='<div id="'.$ti.$key.'" class="tab-pane fade'.$a.'" role="tabpanel" aria-labelledby="'.$tab['title'].'-tab">';
	$section['content'] .= $tab['tab_content'];
	$section['content'] .= '</div>';
	$a="";
 } 
	$section['content'] .= '</div>';
	

/* ###################### */
/* ### end of content ### */
/* ###################### */


// Recommended: Section Label. If not defined, it will be generated from the folder name.
$section['gp_label'] = 'Bootstrap Tabs';

// Optional: Always process values - if set to true, content will always be generated by processing values, even when not logged-in.
// Using this option, sections may have dynamic content.
$section['always_process_values'] = false;

// Optional: Admin UI color label. This is solely used in the editor's section manager ('Page' mode)
$section['gp_color'] = 'blue';

// Optional: Loadable Components, see https://github.com/Typesetter/Typesetter/blob/master/include/tool/Output/Combine.php#L111
//$components = 'colorbox'; // comma separated string. If 'colorbox' is included \gp\tool::AddColorBox() will be called

// Ootional: Additional CSS and JS if needed
//$css_files = array( 'style.css', ); // style.css must reside in this directory (_types/shop_item). Relative and absolute paths are also possible

// $style = 'body { background:red!important; }';

// $js_files = array( 'script.js', ); // script.js must reside in this directory (_types/shop_item). Relative and absolute paths are also possible.

// $javascript = 'var hello_world = "Hello World!";'; // this will add a global js variable 

// $jQueryCode = '$(".hello").on("click", function(){ alert("Click: " + hello_world); });';


/* ############################################################## */
/* ## EXAMPLES for JS to be executed when a section is updated ## */
/* ############################################################## */

/* Example for CurrenSections.onUpdate() function. 'this' refers to the section's jQuery object in the functions context: */
// $javascript = 'CustomSections = { onUpdate : function(){ console.log("CustomSections.onUpdate function called for ", $(this));} };'; 

/* Example for using the delegated CustomSection:updated event */
// $jQueryCode = '$(document).on("CustomSection:updated", "div.GPAREA", function(){ console.log("The event \"CustomSection:updated\" was triggered on section ", $(this)); });'; 

